DROP TABLE IF EXISTS AUTHOR CASCADE;
CREATE TABLE AUTHOR (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR(255),
    AGE INTEGER NOT NULL,
    CARD_NUMBER BIGINT NOT NULL,
    PRIMARY KEY (ID));

insert into author (name, age, card_number)
values('Vladimir Serov', 53, 123456789);
insert into author (name, age, card_number)
values('Margarita Antonova', 39, 123412345);
insert into author (name, age, card_number)
values('Aleksandr Orlov', 45, 987654321);